version: "3"
services:
  heartbreak-ui:
    build:
      context: ./web-ui
      dockerfile: Dockerfile
    image: heartbreak-ui
    ports:
      - "4000:5000"
  heartbreak-backend:
    build:
        context: .
        dockerfile: Dockerfile
    image: heartbreak-backend
    ports:
        - "5000:5000"
